### PR TITLE
Add whitespace between inline elements

### PR DESCRIPTION
**Pull request by denkv**
Otherwise navigation looks like a mess if CSS did not apply.

### CODE REVIEW

**Comment by yamalight** [comment]
That is not going to scale correctly to different screen sizes. It's better to adjust CSS

**Comment by denkv** [comment]
We can hide whitespace with CSS, would that help?

**Comment by yamalight** [comment]
Why not do it right from the beginning and just use css for this?

**Comment by yamalight** [comment]
Okay, let's start with a different question - what problem does this PR solves?

**Comment by denkv** [comment]
screenshot-2019-10-21-1571608903-z456opAJeO
screenshot-2019-10-21-1571608929-O37lN6rwu4
screenshot-2019-10-21-1571608999-jRPzudQvY7

**Comment by denkv** [comment]
An alternative would be to put some block element like `div` around every link.

**Comment by yamalight** [comment]
Closing this as I don't think supporting browsers with less than 0.001% market share makes sense.

**Pull request closed without merging**
