### PR TITLE
WIMUQ.mdx

### PR DESCRIPTION
**Pull request by ElizaSimpson**
Create WIMUQ blog post

### CODE REVIEW

**Comment by yamalight** [comment]
@ElizaSimpson was `WIMUQ.mdx` supposed to be a news article? If yes - it needs to be moved to `pages/news/` folder. As of now - it was created as a separate page

**Comment by ElizaSimpson** [comment]
Ah yes it was. Thought I'd managed that but clearly did something wrong at
the end

**Comment by ElizaSimpson** [comment]
Not sure how to move it?!

**Comment by yamalight** [comment]
@ElizaSimpson I don't think that's doable from web interface. I've moved it for you, will push to live in a few mins.

**Pull request merged**
